version: '2'

services:
  confluence:
    image: asos/confluence
    hostname: confluence
    volumes:
      - /data/atlassian/confluence:/var/atlassian/confluence
    ports:
      - '8090:8090'
      - '8091:8091'
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'CONFLUENCE_PROXY_NAME='
      - 'CONFLUENCE_PROXY_PORT='
      - 'CONFLUENCE_PROXY_SCHEME='
      - 'CONFLUENCE_DELAYED_START='
    labels:
      com.asos.description: "Atlassian Confluence"
      com.asos.service: "confluence"
      io.rancher.scheduler.affinity:host_label: host=atlassian
      io.rancher.container.pull_image: always
