version: '2'
services:
  confluence:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 8090
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
